language: node_js
dist: trusty
node_js: '6'
before_script: npm install
script:
- npm run test
- npm run build
after_success: npm run coverage
deploy:
  provider: npm
  email: sebastian.lzy@gmail.com
  api_key:
    secure: tOhqlfE+w7MH7VJH90TjJ1vM7OfESI2O5cXulJxxB1mGsFPqlZW0V+C77s9AevzawaLbscSHtCFCqZZXDr8Bs7XFEgSHFR88bHFaKlZupdwtempFiEJiAaIQcgxmIhisH5dWN42tC+8W1Vfjn6r0Iej5rDcJm97KlsBp1ACYvOoZxS6O2G25s+2OBHye/XLV5C45g86rkLnZbU4ILRfPnLL5dwXJaTFK9bg5ojX2L/p7xVbVZZDCMIAEDK3LtMj748AZbScHKd1zePbCG0wZmhPDLbEPgCydZ5XQXAh5m7G47uNs+JxTK8F97IBFxJIdtIDhRwXGhwElzy5Bah+KL3eCJ+/9fL/iq2y0dxf/Wv9XuOnKwDgjl0fJ9ebSiGPHBIa7vk1d7GWUSifnx7TnKBNWxlXq4iOsxFl/BhMz3QBiiddgekn2k80qTaljZ1TmUjmgQd1GFwFfDLKpZPwaEbu6BtPZEyopJcHOwc3akFqYy9tvBtdgv4VPzR37AgiQ3L2xYx0TwyXksvLVbE5TuqrffLxjpAJybsaWxmdNS6k9t3zuCfuV9csT1LgdHWkx2sKZwpypb3QgQJ8AXImj4aH6xI6ThymOsd0VQG2TjDOoVBmYIL359MblXxrb1E+xZ+b3xkNLTJv3RWxVSZzfNz4e785Jf4KTXWX4LNDmyco=
  on:
    branch: master
    repo: sebastianlzy/superagent-debugger
